### ISSUE TITLE
[critical] - Requiring cycle

### ISSUE THREAD

**Issue by edgarbonillag** [frammkor/NextDotsChallenge2020#10]
Importar así genera requiring cycles. Esto sucede cuando desde una carpeta principal (en este caso `components`) sin importar el grado de profundidad, importas otro archivo/componente/etc desde el index de esa carpeta.
En este caso es mejor importar directamente el componente desde su carpeta propia.
`import CocktailItem from '../CocktailItem'`;

https://github.com/frammkor/NextDotsChallenge2020/blob/797fd9fc01872b7f09ad46869edd2bf4ab02685a/src/components/CocktailList/index.tsx#L3

**Comment by frammkor** [comment]
Corregido. Gracias.
