### ISSUE TITLE
[Minor] Function call

### ISSUE THREAD

**Issue by ale1313** [frammkor/NextDotsChallenge2020#2]
Cuando llamas a una funcion o metodo en un evento nativo de un componente, no hace falta lo hagas a traves de una anon function, directamente podes llamarlo como una propiedad y va a funcionar igual, ejemplo `onPress={handleCancel}`

https://github.com/frammkor/NextDotsChallenge2020/blob/22f91198dbbeadb3b7d5964eca490d2e8c8b4ec6/src/screens/main/ExploreScreen/index.tsx#L67

**Comment by frammkor** [comment]
Corregido. Gracias!
