### ISSUE TITLE
[Minor] Destructuring the argument

### ISSUE THREAD

**Issue by ale1313** [frammkor/NextDotsChallenge2020#3]
Aca podes destructurar el argumento, cuando tengas una pantalla con muchas propiedades vas a ver que hace mucha diferencia.

https://github.com/frammkor/NextDotsChallenge2020/blob/22f91198dbbeadb3b7d5964eca490d2e8c8b4ec6/src/screens/main/ExploreScreen/index.tsx#L78

**Comment by frammkor** [comment]
el argumento esta destructurado debajo, de la siguiente manera.

const mapStateToProps = (state: any) => {
  const {fetchError, data, fetchIsLoading} = state.cocktailsReducer;
