### ISSUE TITLE
[Minor] Colors in a separated file

### ISSUE THREAD

**Issue by ale1313** [frammkor/NextDotsChallenge2020#4]
Lo ideal seria que pongas los colores que usas en tu app en un archivo separado y que luego los importes, excepto colores basicos como white, black, etc

https://github.com/frammkor/NextDotsChallenge2020/blob/22f91198dbbeadb3b7d5964eca490d2e8c8b4ec6/src/screens/main/ExploreScreen/styles.ts#L34

**Comment by frammkor** [comment]
Agregada carpeta y archivos para manejar los colores de la app.
