### ISSUE TITLE
[critical] - Guardar sólo la data necesaria

### ISSUE THREAD

**Issue by edgarbonillag** [frammkor/NextDotsChallenge2020#5]
De la api llega cada cocktail con mucha información innecesaria, guardar sólo los datos necesarios.

https://github.com/frammkor/NextDotsChallenge2020/blob/797fd9fc01872b7f09ad46869edd2bf4ab02685a/src/store/actions/cocktails.ts#L39

**Comment by frammkor** [comment]
Corregido. En la action se crea un nuevo array de objetos solo con la informacion necesaria y se la pasa a el reducer.
