### ISSUE TITLE
[critical] - Data consistency

### ISSUE THREAD

**Issue by edgarbonillag** [frammkor/NextDotsChallenge2020#7]
Ok, aquí veo que sí intentas aplicar lo que mencioné en el issue #6 pero sucede que el cocktail lo estás guardando completo, es decir, estás guardando muchas más propiedades que las 3 que se definen en el type `Cocktail` (Lo que te menciono en el issue #5) 

https://github.com/frammkor/NextDotsChallenge2020/blob/797fd9fc01872b7f09ad46869edd2bf4ab02685a/src/store/reducers/cocktails/cocktailsReducer.ts#L27

**Comment by frammkor** [comment]
Corregido. Gracias!
