### ISSUE TITLE
[improvement] - No nested ternaries

### ISSUE THREAD

**Issue by edgarbonillag** [frammkor/NextDotsChallenge2020#8]
Realmente en casos de aplicaciones reales, hemos tenido muchos problemas cuando se anidan tantas ternarias seguidas. Sugerencia: Haz este `display` una función y evalúa los casos necesarios con `if`s y `return`s.

Luego, la función la puedes ejecutar como componente  queda también el código más limpio:
Ej: `<display />`

https://github.com/frammkor/NextDotsChallenge2020/blob/797fd9fc01872b7f09ad46869edd2bf4ab02685a/src/screens/main/ExploreScreen/index.tsx#L40

**Comment by frammkor** [comment]
Si, originalmente lo intente asi, pero estaba teniendo problemas con el renderizado del componente. Lo vuelvo a intentar, gracias.

**Comment by frammkor** [comment]
Listo! Gracias!
