### ISSUE TITLE
[improvement] - Cleaner props

### ISSUE THREAD

**Issue by edgarbonillag** [frammkor/NextDotsChallenge2020#9]
Sugerencia, destructurar las props así para código más limpio:
`const InputComponent: React.FC<Props> = ({ toSearch, value }) => { ...`

https://github.com/frammkor/NextDotsChallenge2020/blob/797fd9fc01872b7f09ad46869edd2bf4ab02685a/src/components/InputComponent/index.tsx#L11

**Comment by frammkor** [comment]
Modificado. Gracias.
